version: '3.7'
services:
  mysql:
    image: 'mysql:8.0'
    restart: 'always'
    container_name: 'nestjs-mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestjs-mysql
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
    ports:
      - '3306:3306'
    volumes:
      - .mysql-data:/var/lib/mysql
    networks:
      - internal
networks:
  internal:
    name: internal
    driver: bridge
